[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
vault = "14nzAcFk8UseFJqZ9iYBLRqWMUM67jAEmBTnsG3hc6ik"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
